-- Migration: 0002_flint_a2ui.sql
-- Phase 5 — Flint A2UI Component Registry
--
-- Creates the flint_a2ui schema with all tables in dependency order.
-- Depends on: flint_meta schema (Phase 1), pgvector extension.
-- Applied by fdb-gateway on startup via sqlx migrate.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS flint_a2ui;

-- ─────────────────────────── Core tables ───────────────────────────────────

-- Application registry — must come before components (foreign key target)
CREATE TABLE flint_a2ui.applications (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug                text NOT NULL UNIQUE,
    name                text NOT NULL,
    description         text,
    owner_id            uuid,
    jwt_claims_template jsonb NOT NULL DEFAULT '{}',
    catalog_id          text UNIQUE,      -- URI for A2UI catalog reference
    is_system           boolean NOT NULL DEFAULT false,
    metadata            jsonb NOT NULL DEFAULT '{}',
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Primary component catalog
CREATE TABLE flint_a2ui.components (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slug           text NOT NULL UNIQUE,
    category       text NOT NULL CHECK (category IN (
                       'layout', 'data-display', 'input', 'action', 'navigation', 'feedback', 'system'
                   )),
    primitive_type text NOT NULL,        -- A2UI catalog type string (e.g. 'DataGrid', 'TextInput')
    schema         jsonb NOT NULL,       -- JSON Schema for prop validation
    is_base        boolean NOT NULL DEFAULT false,
    application_id uuid REFERENCES flint_a2ui.applications(id) ON DELETE CASCADE,
    description    text,
    usage_examples jsonb,
    design_tokens  jsonb,
    metadata       jsonb NOT NULL DEFAULT '{}',
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- Design system records (W3C Design Token format in `tokens` JSONB)
CREATE TABLE flint_a2ui.design_systems (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid REFERENCES flint_a2ui.applications(id) ON DELETE CASCADE,
    slug           text NOT NULL UNIQUE,
    name           text NOT NULL,
    bundle_url     text,
    tokens         jsonb NOT NULL DEFAULT '{}',
    metadata       jsonb NOT NULL DEFAULT '{}',
    created_at     timestamptz NOT NULL DEFAULT now()
);

-- pgvector embeddings for semantic search (populated by p5-c004)
CREATE TABLE flint_a2ui.embeddings (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    component_id uuid NOT NULL REFERENCES flint_a2ui.components(id) ON DELETE CASCADE,
    embedding    vector(1536) NOT NULL,
    entity_type  text NOT NULL DEFAULT 'component',
    aspect       text NOT NULL DEFAULT 'description',  -- 'description' | 'usage' | 'props'
    model        text NOT NULL DEFAULT 'text-embedding-3-large',
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Prop schemas per component (separate table for query efficiency)
CREATE TABLE flint_a2ui.schemas (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    component_id   uuid NOT NULL REFERENCES flint_a2ui.components(id) ON DELETE CASCADE,
    schema_version text NOT NULL DEFAULT '1.0',
    json_schema    jsonb NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
);

-- DB table → component bindings (auto-generated by trigger in p5-c003)
CREATE TABLE flint_a2ui.bindings (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    table_schema   text NOT NULL,
    table_name     text NOT NULL,
    component_id   uuid NOT NULL REFERENCES flint_a2ui.components(id),
    binding_type   text NOT NULL CHECK (binding_type IN ('form', 'grid', 'detail', 'card')),
    auto_generated boolean NOT NULL DEFAULT true,
    config         jsonb NOT NULL DEFAULT '{}',
    created_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (table_schema, table_name, binding_type)
);

-- Append-only audit/event log (RLS enforces no UPDATE/DELETE)
CREATE TABLE flint_a2ui.events (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid REFERENCES flint_a2ui.applications(id),
    event_type     text NOT NULL,
    actor          text,
    object         text,
    action         text,
    result         boolean,
    details        jsonb,
    created_at     timestamptz NOT NULL DEFAULT now()
);

-- Event-driven assembly rules
CREATE TABLE flint_a2ui.assembly_rules (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES flint_a2ui.applications(id),
    event_type     text NOT NULL,
    event_filter   jsonb NOT NULL DEFAULT '{}',
    assembly_config jsonb NOT NULL,
    priority       int NOT NULL DEFAULT 100,
    is_active      boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- Role hierarchy (used for scoped component access)
CREATE TABLE flint_a2ui.roles (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES flint_a2ui.applications(id),
    slug           text NOT NULL,
    name           text NOT NULL,
    parent_role_id uuid REFERENCES flint_a2ui.roles(id),
    keto_namespace text,
    keto_relation  text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (application_id, slug)
);

-- User → role assignments (user_id from JWT claims)
CREATE TABLE flint_a2ui.role_assignments (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES flint_a2ui.applications(id),
    role_id        uuid NOT NULL REFERENCES flint_a2ui.roles(id),
    user_id        text NOT NULL,
    granted_by     text,
    granted_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (application_id, role_id, user_id)
);

-- ────────────────────────── Indexes ────────────────────────────────────────

-- HNSW index for approximate nearest-neighbor search on component embeddings.
-- m=16, ef_construction=64: balanced recall/build-time for catalog-scale vectors.
CREATE INDEX idx_embeddings_hnsw ON flint_a2ui.embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE INDEX idx_components_category ON flint_a2ui.components (category);
CREATE INDEX idx_components_is_base ON flint_a2ui.components (is_base) WHERE is_base = true;
CREATE INDEX idx_bindings_table ON flint_a2ui.bindings (table_schema, table_name);
CREATE INDEX idx_events_application ON flint_a2ui.events (application_id, created_at DESC);
CREATE INDEX idx_role_assignments_user ON flint_a2ui.role_assignments (application_id, user_id);

-- ───────────────────── Semantic search stub (p5-c004 populates) ────────────

-- Stub implementation: functional for existing embeddings; p5-c004 adds the
-- embedding generation pipeline that populates the embeddings table.
CREATE OR REPLACE FUNCTION flint_a2ui.semantic_search(
    query_embedding vector(1536),
    result_limit    int DEFAULT 10
) RETURNS TABLE (
    component_id uuid,
    slug         text,
    similarity   float
) LANGUAGE sql STABLE AS $$
    SELECT
        c.id,
        c.slug,
        1.0 - (e.embedding <=> query_embedding) AS similarity
    FROM flint_a2ui.embeddings e
    JOIN flint_a2ui.components c ON c.id = e.component_id
    WHERE e.aspect = 'description'
    ORDER BY e.embedding <=> query_embedding
    LIMIT result_limit;
$$;

-- ─────────────────────────── RLS policies ───────────────────────────────────

-- Components: base components visible to all; app-specific components scoped
-- by role_assignments. current_setting true flag = NULL (not error) when GUC unset.
ALTER TABLE flint_a2ui.components ENABLE ROW LEVEL SECURITY;

CREATE POLICY component_access ON flint_a2ui.components
    FOR ALL USING (
        is_base = true
        OR application_id IS NULL
        OR application_id IN (
            SELECT application_id FROM flint_a2ui.role_assignments
            WHERE user_id = (current_setting('app.jwt_claims', true)::jsonb)->'flint'->>'user_id'
        )
    );

-- Events: append-only. INSERT allowed; UPDATE and DELETE explicitly denied.
ALTER TABLE flint_a2ui.events ENABLE ROW LEVEL SECURITY;

CREATE POLICY event_insert ON flint_a2ui.events
    FOR INSERT WITH CHECK (true);

CREATE POLICY event_select ON flint_a2ui.events
    FOR SELECT USING (
        application_id IS NULL
        OR application_id IN (
            SELECT application_id FROM flint_a2ui.role_assignments
            WHERE user_id = (current_setting('app.jwt_claims', true)::jsonb)->'flint'->>'user_id'
        )
    );

-- Explicitly deny mutation of audit records.
CREATE POLICY event_no_update ON flint_a2ui.events FOR UPDATE USING (false);
CREATE POLICY event_no_delete ON flint_a2ui.events FOR DELETE USING (false);

-- ──────────────────────────── Grants ────────────────────────────────────────

GRANT USAGE ON SCHEMA flint_a2ui TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA flint_a2ui TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA flint_a2ui TO service_role;
GRANT EXECUTE ON FUNCTION flint_a2ui.semantic_search TO service_role;

-- ────────────────────────── Seed data ───────────────────────────────────────

-- Seeded in task 7 (is_system column added above).
-- Base components seeded by p5-c002-base-components-seed (separate migration).
INSERT INTO flint_a2ui.applications (slug, name, description, is_system)
VALUES
    ('flint-admin',      'Flint Admin',      'Administrative interface', true),
    ('flint-playground', 'Flint Playground', 'Developer sandbox',        true)
ON CONFLICT (slug) DO NOTHING;
