//! The pure DDL generator (FFS-001 §8 tasks 1.3–1.5).
//!
//! `generate(spec, live)` validates the spec, diffs it against the live
//! namespace, and emits additive-only DDL (FFS-001 D6): `CREATE SCHEMA IF NOT
//! EXISTS`, `CREATE TABLE`, `ADD COLUMN IF NOT EXISTS` (nullable-or-defaulted
//! only), `CREATE INDEX IF NOT EXISTS`, and — for tenant-scoped tables — the
//! fixed RLS block (FFS-001 D5): `tenant_id`, ENABLE+FORCE, four policies,
//! tenant index, grant. No destructive statement kind exists in this module.
//!
//! Diff limits, stated honestly: [`fdb_domain::TableMeta`] carries columns
//! and `rls_enabled` but not indexes or policies, so on an *existing* table
//! index/policy statements are re-emitted with idempotent guards instead of
//! being diffed away — `noop` is therefore exact for tables and columns and
//! conservative (may be `false` on an already-satisfied schema) when the spec
//! declares indexes on pre-existing tables. Exact replay of an applied plan
//! is caught earlier by the ledger (`alreadyApplied`), not here.

use fdb_domain::provision::{
    validate_spec, ColumnSpec, ColumnType, Namespace, Operation, OperationKind, Plan, SchemaSpec,
    SpecError, TableSpec,
};
use fdb_domain::TableMeta;

/// Generation failure: an invalid spec, a non-additive-safe change, or the
/// (structurally impossible) canonicalization failure.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum PlanError {
    /// The spec failed validation; see [`SpecError`].
    #[error("invalid spec: {0}")]
    Spec(#[from] SpecError),
    /// Adding this column to an existing table is not additive-safe: it is
    /// NOT NULL with no default, so existing rows could not satisfy it.
    #[error(
        "table `{table}`: adding non-nullable column `{column}` without a default \
         is not additive-safe (FFS-001 D6)"
    )]
    UnsafeAddColumn {
        /// The table gaining the column.
        table: String,
        /// The offending column.
        column: String,
    },
    /// The spec could not be canonicalized for hashing.
    #[error("spec canonicalization failed: {0}")]
    Canonicalize(String),
}

/// Generate a [`Plan`] from a validated spec and the live namespace state.
///
/// Pure and deterministic: same inputs ⇒ same operations, DDL text, and hash.
///
/// # Errors
///
/// [`PlanError::Spec`] for any validation failure, [`PlanError::UnsafeAddColumn`]
/// when an existing table would gain a NOT NULL column without a default, and
/// [`PlanError::Canonicalize`] if hashing fails.
pub fn generate(spec: &SchemaSpec, live: &[TableMeta]) -> Result<Plan, PlanError> {
    let warnings = validate_spec(spec)?;
    let hash = super::hash::plan_hash(spec)?;
    let ns = &spec.namespace;

    let mut statements: Vec<String> = Vec::new();
    let mut operations: Vec<Operation> = Vec::new();

    let schema_exists = live.iter().any(|t| t.schema == ns.as_str());
    operations.push(Operation {
        kind: OperationKind::CreateSchema,
        target: ns.as_str().to_owned(),
        exists: schema_exists,
    });
    if !schema_exists {
        statements.push(format!("CREATE SCHEMA IF NOT EXISTS {ns};"));
    }

    for table in &spec.tables {
        let live_table = live
            .iter()
            .find(|t| t.schema == ns.as_str() && t.name == table.name);
        match live_table {
            None => emit_create_table(ns, table, &mut statements, &mut operations),
            Some(existing) => {
                emit_table_diff(ns, table, existing, &mut statements, &mut operations)?;
            }
        }
    }

    let noop = statements.is_empty();
    let ddl = if noop {
        String::new()
    } else {
        format!(
            "-- generated by FFS-001 schema provisioning (p17); additive-only, replay-safe\n\n{}",
            statements.join("\n\n")
        )
    };

    Ok(Plan {
        namespace: ns.clone(),
        operations,
        ddl,
        warnings,
        noop,
        hash,
    })
}

fn render_column(col: &ColumnSpec) -> String {
    let mut out = format!("    {} {}", col.name, col.column_type.sql_name());
    if !col.nullable {
        out.push_str(" NOT NULL");
    }
    if let Some(default) = &col.default {
        out.push_str(" DEFAULT ");
        out.push_str(default);
    }
    out
}

fn emit_create_table(
    ns: &Namespace,
    table: &TableSpec,
    statements: &mut Vec<String>,
    operations: &mut Vec<Operation>,
) {
    let t = &table.name;
    let mut lines: Vec<String> = table.columns.iter().map(render_column).collect();
    if table.tenant_scoped {
        lines.push("    tenant_id text NOT NULL".to_owned());
    }
    let pk: Vec<&str> = table
        .columns
        .iter()
        .filter(|c| c.primary_key)
        .map(|c| c.name.as_str())
        .collect();
    if !pk.is_empty() {
        lines.push(format!("    PRIMARY KEY ({})", pk.join(", ")));
    }
    statements.push(format!("CREATE TABLE {ns}.{t} (\n{}\n);", lines.join(",\n")));
    operations.push(Operation {
        kind: OperationKind::CreateTable,
        target: format!("{ns}.{t}"),
        exists: false,
    });

    if let Some(comment) = &table.comment {
        let escaped = comment.replace('\'', "''");
        statements.push(format!("COMMENT ON TABLE {ns}.{t} IS '{escaped}';"));
        operations.push(Operation {
            kind: OperationKind::Comment,
            target: format!("{ns}.{t}"),
            exists: false,
        });
    }

    if table.tenant_scoped {
        emit_tenant_block(ns, t, statements, operations);
    }
    for idx in &table.indexes {
        emit_index(ns, t, &idx.name, &idx.columns, idx.unique, statements, operations);
    }
}

fn emit_table_diff(
    ns: &Namespace,
    table: &TableSpec,
    existing: &TableMeta,
    statements: &mut Vec<String>,
    operations: &mut Vec<Operation>,
) -> Result<(), PlanError> {
    let t = &table.name;

    // tenant_id is an implicit NOT-NULL-no-default column on scoped tables;
    // modelling it this way makes "existing table newly declared scoped"
    // fail the additive-safety check naturally instead of silently emitting
    // a column existing rows cannot satisfy.
    let tenant_col = ColumnSpec {
        name: "tenant_id".to_owned(),
        column_type: ColumnType::Text,
        nullable: false,
        primary_key: false,
        default: None,
    };
    let mut desired: Vec<&ColumnSpec> = table.columns.iter().collect();
    if table.tenant_scoped {
        desired.push(&tenant_col);
    }

    for col in desired {
        let already = existing.columns.iter().any(|c| c.name == col.name);
        if already {
            continue;
        }
        if !col.nullable && col.default.is_none() {
            return Err(PlanError::UnsafeAddColumn {
                table: t.clone(),
                column: col.name.clone(),
            });
        }
        statements.push(format!(
            "ALTER TABLE {ns}.{t} ADD COLUMN IF NOT EXISTS{};",
            render_column(col).replacen("    ", " ", 1)
        ));
        operations.push(Operation {
            kind: OperationKind::AddColumn,
            target: format!("{ns}.{t}.{}", col.name),
            exists: false,
        });
    }

    if table.tenant_scoped && !existing.rls_enabled {
        emit_tenant_block(ns, t, statements, operations);
    }

    // Index existence is not introspectable from TableMeta (module docs):
    // re-emit with IF NOT EXISTS guards. Harmless on replay; a genuinely new
    // index gets created.
    for idx in &table.indexes {
        emit_index(ns, t, &idx.name, &idx.columns, idx.unique, statements, operations);
    }
    Ok(())
}

/// The fixed tenant block (FFS-001 D5, template from §5): the caller cannot
/// supply, override, or disable any statement in here.
fn emit_tenant_block(
    ns: &Namespace,
    t: &str,
    statements: &mut Vec<String>,
    operations: &mut Vec<Operation>,
) {
    statements.push(format!("ALTER TABLE {ns}.{t} ENABLE ROW LEVEL SECURITY;"));
    statements.push(format!("ALTER TABLE {ns}.{t} FORCE ROW LEVEL SECURITY;"));
    operations.push(Operation {
        kind: OperationKind::EnableRls,
        target: format!("{ns}.{t}"),
        exists: false,
    });

    let tenant_expr = "current_setting('request.jwt.claims', true)::json ->> 'tenant_id'";
    let policies: [(&str, String); 4] = [
        (
            "select",
            format!("FOR SELECT TO authenticated\n            USING (tenant_id = {tenant_expr})"),
        ),
        (
            "insert",
            format!(
                "FOR INSERT TO authenticated\n            WITH CHECK (tenant_id = {tenant_expr})"
            ),
        ),
        (
            "update",
            format!(
                "FOR UPDATE TO authenticated\n            USING (tenant_id = {tenant_expr})\n            WITH CHECK (tenant_id = {tenant_expr})"
            ),
        ),
        (
            "delete",
            format!("FOR DELETE TO authenticated\n            USING (tenant_id = {tenant_expr})"),
        ),
    ];
    for (verb, body) in policies {
        let policy = format!("{t}_tenant_{verb}");
        statements.push(format!(
            "DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = '{ns}' AND tablename = '{t}' AND policyname = '{policy}'\n    ) THEN\n        CREATE POLICY {policy} ON {ns}.{t} {body};\n    END IF;\nEND\n$policy$;"
        ));
        operations.push(Operation {
            kind: OperationKind::CreatePolicy,
            target: policy,
            exists: false,
        });
    }

    emit_index(
        ns,
        t,
        &format!("{t}_tenant_idx"),
        std::slice::from_ref(&"tenant_id".to_owned()),
        false,
        statements,
        operations,
    );

    statements.push(format!(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON {ns}.{t} TO authenticated;"
    ));
    operations.push(Operation {
        kind: OperationKind::Grant,
        target: "authenticated".to_owned(),
        exists: false,
    });
}

fn emit_index(
    ns: &Namespace,
    t: &str,
    name: &str,
    columns: &[String],
    unique: bool,
    statements: &mut Vec<String>,
    operations: &mut Vec<Operation>,
) {
    let unique_kw = if unique { "UNIQUE " } else { "" };
    statements.push(format!(
        "CREATE {unique_kw}INDEX IF NOT EXISTS {name} ON {ns}.{t} ({});",
        columns.join(", ")
    ));
    operations.push(Operation {
        kind: OperationKind::CreateIndex,
        target: name.to_owned(),
        exists: false,
    });
}
