//! Unit tests for the DDL generator (FFS-001 §8 Phase 1 gate): DDL
//! snapshots, diff/noop, hash stability, and the injection corpus.

#![allow(clippy::expect_used)]

use fdb_domain::provision::{
    ColumnSpec, ColumnType, IndexSpec, Namespace, OperationKind, SchemaSpec, SpecError, TableSpec,
};
use fdb_domain::{ColumnMeta, TableMeta};

use super::ddl::{generate, PlanError};
use super::hash::plan_hash;

fn col(name: &str, ty: ColumnType, nullable: bool, pk: bool, default: Option<&str>) -> ColumnSpec {
    ColumnSpec {
        name: name.into(),
        column_type: ty,
        nullable,
        primary_key: pk,
        default: default.map(str::to_owned),
    }
}

fn tenant_table(name: &str) -> TableSpec {
    TableSpec {
        name: name.into(),
        comment: None,
        tenant_scoped: true,
        acknowledge_unscoped: false,
        columns: vec![
            col("id", ColumnType::Text, false, true, None),
            col("payload", ColumnType::Jsonb, false, false, Some("'{}'")),
        ],
        indexes: vec![],
        api_exposed: true,
    }
}

fn spec(ns: &str, tables: Vec<TableSpec>) -> SchemaSpec {
    SchemaSpec {
        namespace: Namespace(ns.into()),
        tables,
    }
}

fn live_table(ns: &str, name: &str, cols: &[(&str, &str, bool)], rls: bool) -> TableMeta {
    TableMeta {
        schema: ns.into(),
        name: name.into(),
        columns: cols
            .iter()
            .map(|(n, ty, nullable)| ColumnMeta {
                name: (*n).into(),
                sql_type: (*ty).into(),
                nullable: *nullable,
            })
            .collect(),
        primary_key: vec!["id".into()],
        rls_enabled: rls,
    }
}

#[test]
fn snapshot_tenant_scoped_create_table() {
    let mut t = tenant_table("watch");
    t.indexes.push(IndexSpec {
        name: "watch_payload_idx".into(),
        columns: vec!["id".into(), "payload".into()],
        unique: true,
    });
    let plan = generate(&spec("acme_app", vec![t]), &[]).expect("valid spec");

    let expected = "-- generated by FFS-001 schema provisioning (p17); additive-only, replay-safe\n\n\
CREATE SCHEMA IF NOT EXISTS acme_app;\n\n\
CREATE TABLE acme_app.watch (\n    id text NOT NULL,\n    payload jsonb NOT NULL DEFAULT '{}',\n    tenant_id text NOT NULL,\n    PRIMARY KEY (id)\n);\n\n\
ALTER TABLE acme_app.watch ENABLE ROW LEVEL SECURITY;\n\n\
ALTER TABLE acme_app.watch FORCE ROW LEVEL SECURITY;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_select'\n    ) THEN\n        CREATE POLICY watch_tenant_select ON acme_app.watch FOR SELECT TO authenticated\n            USING (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_insert'\n    ) THEN\n        CREATE POLICY watch_tenant_insert ON acme_app.watch FOR INSERT TO authenticated\n            WITH CHECK (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_update'\n    ) THEN\n        CREATE POLICY watch_tenant_update ON acme_app.watch FOR UPDATE TO authenticated\n            USING (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id')\n            WITH CHECK (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_delete'\n    ) THEN\n        CREATE POLICY watch_tenant_delete ON acme_app.watch FOR DELETE TO authenticated\n            USING (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
CREATE INDEX IF NOT EXISTS watch_tenant_idx ON acme_app.watch (tenant_id);\n\n\
GRANT SELECT, INSERT, UPDATE, DELETE ON acme_app.watch TO authenticated;\n\n\
CREATE UNIQUE INDEX IF NOT EXISTS watch_payload_idx ON acme_app.watch (id, payload);";

    assert_eq!(plan.ddl, expected);
    assert!(!plan.noop);
    assert!(plan.warnings.is_empty());

    let kinds: Vec<OperationKind> = plan.operations.iter().map(|o| o.kind).collect();
    assert_eq!(
        kinds,
        vec![
            OperationKind::CreateSchema,
            OperationKind::CreateTable,
            OperationKind::EnableRls,
            OperationKind::CreatePolicy,
            OperationKind::CreatePolicy,
            OperationKind::CreatePolicy,
            OperationKind::CreatePolicy,
            OperationKind::CreateIndex, // generated tenant index
            OperationKind::Grant,
            OperationKind::CreateIndex, // caller-declared unique index
        ]
    );
}

#[test]
fn comment_is_escaped_not_interpolated() {
    let mut t = tenant_table("watch");
    t.comment = Some("it's a'; DROP TABLE x; --".into());
    let plan = generate(&spec("acme_app", vec![t]), &[]).expect("valid spec");
    assert!(plan
        .ddl
        .contains("COMMENT ON TABLE acme_app.watch IS 'it''s a''; DROP TABLE x; --';"));
}

#[test]
fn noop_when_live_schema_satisfies_spec() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[("id", "text", false), ("payload", "jsonb", false), ("tenant_id", "text", false)],
        true,
    )];
    let plan = generate(&spec("acme_app", vec![tenant_table("watch")]), &live).expect("valid");
    assert!(plan.noop, "satisfied schema must be a noop; got ddl:\n{}", plan.ddl);
    assert_eq!(plan.ddl, "");
    // Diff facts are still reported: schema and (implicitly) table exist.
    assert!(plan.operations.iter().any(|o| o.kind == OperationKind::CreateSchema && o.exists));
}

#[test]
fn add_column_diff_is_additive_and_guarded() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[("id", "text", false), ("tenant_id", "text", false)],
        true,
    )];
    let mut t = tenant_table("watch");
    t.columns.push(col("filed_at", ColumnType::Timestamptz, true, false, None));
    let plan = generate(&spec("acme_app", vec![t]), &live).expect("valid");
    // `payload` has a default, `filed_at` is nullable — both additive-safe.
    assert!(plan
        .ddl
        .contains("ALTER TABLE acme_app.watch ADD COLUMN IF NOT EXISTS payload jsonb NOT NULL DEFAULT '{}';"));
    assert!(plan
        .ddl
        .contains("ALTER TABLE acme_app.watch ADD COLUMN IF NOT EXISTS filed_at timestamptz;"));
    assert!(!plan.ddl.contains("CREATE TABLE"), "existing table must not be re-created");
}

#[test]
fn unsafe_add_column_is_refused() {
    let live = [live_table("acme_app", "watch", &[("id", "text", false), ("tenant_id", "text", false)], true)];
    let mut t = tenant_table("watch");
    t.columns.push(col("required_no_default", ColumnType::Text, false, false, None));
    let err = generate(&spec("acme_app", vec![t]), &live).expect_err("must refuse");
    assert!(matches!(
        err,
        PlanError::UnsafeAddColumn { ref column, .. } if column == "required_no_default"
    ));
}

#[test]
fn existing_unscoped_table_newly_declared_scoped_is_refused() {
    // tenant_id is implicit NOT NULL with no default: an existing table
    // cannot gain it additively, and the generator must say so rather than
    // emit DDL that fails (or worse, silently weaken the column).
    let live = [live_table("acme_app", "watch", &[("id", "text", false)], false)];
    let err = generate(&spec("acme_app", vec![tenant_table("watch")]), &live)
        .expect_err("must refuse implicit tenant_id on existing table");
    assert!(matches!(
        err,
        PlanError::UnsafeAddColumn { ref column, .. } if column == "tenant_id"
    ));
}

#[test]
fn rls_drift_on_existing_scoped_table_is_repaired() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[("id", "text", false), ("payload", "jsonb", false), ("tenant_id", "text", false)],
        false, // RLS off: the drift this test repairs
    )];
    let plan = generate(&spec("acme_app", vec![tenant_table("watch")]), &live).expect("valid");
    assert!(plan.ddl.contains("FORCE ROW LEVEL SECURITY"));
    assert!(plan.ddl.contains("watch_tenant_select"));
    assert!(!plan.ddl.contains("CREATE TABLE"));
}

#[test]
fn hash_is_stable_across_input_field_reordering() {
    let a: SchemaSpec = serde_json::from_str(
        r#"{"namespace":"acme_app","tables":[{"name":"t","tenantScoped":true,
            "columns":[{"name":"id","type":"text","nullable":false,"primaryKey":true}]}]}"#,
    )
    .expect("parse a");
    let b: SchemaSpec = serde_json::from_str(
        r#"{"tables":[{"columns":[{"primaryKey":true,"nullable":false,"type":"text","name":"id"}],
            "tenantScoped":true,"name":"t"}],"namespace":"acme_app"}"#,
    )
    .expect("parse b");
    assert_eq!(
        plan_hash(&a).expect("hash a"),
        plan_hash(&b).expect("hash b"),
        "JSON field order must not affect the hash"
    );

    let c: SchemaSpec = serde_json::from_str(
        r#"{"namespace":"acme_app","tables":[{"name":"t","tenantScoped":true,
            "columns":[{"name":"id","type":"uuid","nullable":false,"primaryKey":true}]}]}"#,
    )
    .expect("parse c");
    assert_ne!(
        plan_hash(&a).expect("hash a"),
        plan_hash(&c).expect("hash c"),
        "a semantic change (column type) must change the hash"
    );
}

#[test]
fn injection_corpus_fails_before_any_generation() {
    let cases: Vec<SchemaSpec> = vec![
        // "; DROP TABLE" in a table name
        spec("acme_app", vec![tenant_table("watch\"; DROP TABLE users; --")]),
        // quoted identifier
        spec("acme_app", vec![tenant_table("\"watch\"")]),
        // -- comment terminator in an index name
        {
            let mut t = tenant_table("watch");
            t.indexes.push(IndexSpec { name: "idx--evil".into(), columns: vec!["id".into()], unique: false });
            spec("acme_app", vec![t])
        },
        // nested $$ in an index column
        {
            let mut t = tenant_table("watch");
            t.indexes.push(IndexSpec { name: "idx_ok".into(), columns: vec!["$$body$$".into()], unique: false });
            spec("acme_app", vec![t])
        },
        // unicode homoglyph (non-ASCII) column
        {
            let mut t = tenant_table("watch");
            t.columns.push(col("pаyload", ColumnType::Text, true, false, None)); // Cyrillic а
            spec("acme_app", vec![t])
        },
        // reserved namespace
        spec("flint_meta", vec![tenant_table("watch")]),
        // hostile default expression
        {
            let mut t = tenant_table("watch");
            t.columns.push(col("d", ColumnType::Text, true, false, Some("''; DROP TABLE x; --'")));
            spec("acme_app", vec![t])
        },
    ];
    for (i, s) in cases.iter().enumerate() {
        let err = generate(s, &[]).expect_err(&format!("corpus case {i} must be rejected"));
        assert!(matches!(err, PlanError::Spec(_)), "case {i} rejected at validation, got {err:?}");
    }
}

#[test]
fn reserved_namespace_error_names_the_namespace() {
    let err = generate(&spec("pg_catalog", vec![tenant_table("t")]), &[]).expect_err("reserved");
    assert!(matches!(
        err,
        PlanError::Spec(SpecError::ReservedNamespace(ref ns)) if ns == "pg_catalog"
    ));
}
