//! Unit tests for the DDL generator (FFS-001 §8 Phase 1 gate): DDL
//! snapshots, diff/noop, hash stability, and the injection corpus.

#![allow(clippy::expect_used)]

use fdb_domain::provision::{
    ColumnSpec, ColumnType, IndexSpec, Namespace, OperationKind, SchemaSpec, SpecError, TableSpec,
};
use fdb_domain::{ColumnMeta, TableMeta};

use super::ddl::{generate, PlanError};

/// Hash of a spec generated against a given live state — the tests reason
/// about plan hashes exactly the way the gateway does: via `generate`.
fn hash_of(spec: &SchemaSpec, live: &[TableMeta]) -> fdb_domain::provision::PlanHash {
    generate(spec, live).expect("valid spec").hash
}

fn col(name: &str, ty: ColumnType, nullable: bool, pk: bool, default: Option<&str>) -> ColumnSpec {
    ColumnSpec {
        name: name.into(),
        column_type: ty,
        nullable,
        primary_key: pk,
        default: default.map(str::to_owned),
    }
}

fn tenant_table(name: &str) -> TableSpec {
    TableSpec {
        name: name.into(),
        comment: None,
        tenant_scoped: true,
        acknowledge_unscoped: false,
        columns: vec![
            col("id", ColumnType::Text, false, true, None),
            col("payload", ColumnType::Jsonb, false, false, Some("'{}'")),
        ],
        indexes: vec![],
        api_exposed: true,
    }
}

fn spec(ns: &str, tables: Vec<TableSpec>) -> SchemaSpec {
    SchemaSpec {
        namespace: Namespace(ns.into()),
        tables,
    }
}

fn live_table(ns: &str, name: &str, cols: &[(&str, &str, bool)], rls: bool) -> TableMeta {
    TableMeta {
        schema: ns.into(),
        name: name.into(),
        columns: cols
            .iter()
            .map(|(n, ty, nullable)| ColumnMeta {
                name: (*n).into(),
                sql_type: (*ty).into(),
                nullable: *nullable,
            })
            .collect(),
        primary_key: vec!["id".into()],
        rls_enabled: rls,
    }
}

#[test]
fn snapshot_tenant_scoped_create_table() {
    let mut t = tenant_table("watch");
    t.indexes.push(IndexSpec {
        name: "watch_payload_idx".into(),
        columns: vec!["id".into(), "payload".into()],
        unique: true,
    });
    let plan = generate(&spec("acme_app", vec![t]), &[]).expect("valid spec");

    let expected = "-- generated by FFS-001 schema provisioning (p17); additive-only, replay-safe\n\n\
CREATE TABLE acme_app.watch (\n    id text NOT NULL,\n    payload jsonb NOT NULL DEFAULT '{}',\n    tenant_id text NOT NULL,\n    PRIMARY KEY (id)\n);\n\n\
ALTER TABLE acme_app.watch ENABLE ROW LEVEL SECURITY;\n\n\
ALTER TABLE acme_app.watch FORCE ROW LEVEL SECURITY;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_select'\n    ) THEN\n        CREATE POLICY watch_tenant_select ON acme_app.watch FOR SELECT TO authenticated\n            USING (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_insert'\n    ) THEN\n        CREATE POLICY watch_tenant_insert ON acme_app.watch FOR INSERT TO authenticated\n            WITH CHECK (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_update'\n    ) THEN\n        CREATE POLICY watch_tenant_update ON acme_app.watch FOR UPDATE TO authenticated\n            USING (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id')\n            WITH CHECK (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
DO $policy$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_policies\n        WHERE schemaname = 'acme_app' AND tablename = 'watch' AND policyname = 'watch_tenant_delete'\n    ) THEN\n        CREATE POLICY watch_tenant_delete ON acme_app.watch FOR DELETE TO authenticated\n            USING (tenant_id = current_setting('request.jwt.claims', true)::json ->> 'tenant_id');\n    END IF;\nEND\n$policy$;\n\n\
CREATE INDEX IF NOT EXISTS watch_tenant_idx ON acme_app.watch (tenant_id);\n\n\
GRANT SELECT, INSERT, UPDATE, DELETE ON acme_app.watch TO authenticated;\n\n\
CREATE UNIQUE INDEX IF NOT EXISTS watch_payload_idx ON acme_app.watch (id, payload);";

    assert_eq!(plan.ddl, expected);
    assert!(!plan.noop);
    assert!(plan.warnings.is_empty());

    let kinds: Vec<OperationKind> = plan.operations.iter().map(|o| o.kind).collect();
    assert_eq!(
        kinds,
        vec![
            OperationKind::CreateTable,
            OperationKind::EnableRls,
            OperationKind::CreatePolicy,
            OperationKind::CreatePolicy,
            OperationKind::CreatePolicy,
            OperationKind::CreatePolicy,
            OperationKind::CreateIndex, // generated tenant index
            OperationKind::Grant,
            OperationKind::CreateIndex, // caller-declared unique index
        ]
    );
}

#[test]
fn comment_is_escaped_not_interpolated() {
    let mut t = tenant_table("watch");
    t.comment = Some("it's a'; DROP TABLE x; --".into());
    let plan = generate(&spec("acme_app", vec![t]), &[]).expect("valid spec");
    assert!(plan
        .ddl
        .contains("COMMENT ON TABLE acme_app.watch IS 'it''s a''; DROP TABLE x; --';"));
}

#[test]
fn noop_when_live_schema_satisfies_spec() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[
            ("id", "text", false),
            ("payload", "jsonb", false),
            ("tenant_id", "text", false),
        ],
        true,
    )];
    let plan = generate(&spec("acme_app", vec![tenant_table("watch")]), &live).expect("valid");
    assert!(
        plan.noop,
        "satisfied schema must be a noop; got ddl:\n{}",
        plan.ddl
    );
    assert_eq!(plan.ddl, "");
    // A satisfied spec yields no operations at all (no create_schema entry:
    // schema lifecycle is operator-owned, never part of a plan).
    assert!(plan.operations.is_empty());
}

#[test]
fn add_column_diff_is_additive_and_guarded() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[("id", "text", false), ("tenant_id", "text", false)],
        true,
    )];
    let mut t = tenant_table("watch");
    t.columns
        .push(col("filed_at", ColumnType::Timestamptz, true, false, None));
    let plan = generate(&spec("acme_app", vec![t]), &live).expect("valid");
    // `payload` has a default, `filed_at` is nullable — both additive-safe.
    assert!(plan.ddl.contains(
        "ALTER TABLE acme_app.watch ADD COLUMN IF NOT EXISTS payload jsonb NOT NULL DEFAULT '{}';"
    ));
    assert!(plan
        .ddl
        .contains("ALTER TABLE acme_app.watch ADD COLUMN IF NOT EXISTS filed_at timestamptz;"));
    assert!(
        !plan.ddl.contains("CREATE TABLE"),
        "existing table must not be re-created"
    );
}

#[test]
fn unsafe_add_column_is_refused() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[("id", "text", false), ("tenant_id", "text", false)],
        true,
    )];
    let mut t = tenant_table("watch");
    t.columns.push(col(
        "required_no_default",
        ColumnType::Text,
        false,
        false,
        None,
    ));
    let err = generate(&spec("acme_app", vec![t]), &live).expect_err("must refuse");
    assert!(matches!(
        err,
        PlanError::UnsafeAddColumn { ref column, .. } if column == "required_no_default"
    ));
}

#[test]
fn existing_unscoped_table_newly_declared_scoped_is_refused() {
    // tenant_id is implicit NOT NULL with no default: an existing table
    // cannot gain it additively, and the generator must say so rather than
    // emit DDL that fails (or worse, silently weaken the column).
    let live = [live_table(
        "acme_app",
        "watch",
        &[("id", "text", false)],
        false,
    )];
    let err = generate(&spec("acme_app", vec![tenant_table("watch")]), &live)
        .expect_err("must refuse implicit tenant_id on existing table");
    assert!(matches!(
        err,
        PlanError::UnsafeAddColumn { ref column, .. } if column == "tenant_id"
    ));
}

#[test]
fn rls_drift_on_existing_scoped_table_is_repaired() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[
            ("id", "text", false),
            ("payload", "jsonb", false),
            ("tenant_id", "text", false),
        ],
        false, // RLS off: the drift this test repairs
    )];
    let plan = generate(&spec("acme_app", vec![tenant_table("watch")]), &live).expect("valid");
    assert!(plan.ddl.contains("FORCE ROW LEVEL SECURITY"));
    assert!(plan.ddl.contains("watch_tenant_select"));
    assert!(!plan.ddl.contains("CREATE TABLE"));
}

#[test]
fn hash_is_stable_across_input_field_reordering() {
    let a: SchemaSpec = serde_json::from_str(
        r#"{"namespace":"acme_app","tables":[{"name":"t","tenantScoped":true,
            "columns":[{"name":"id","type":"text","nullable":false,"primaryKey":true}]}]}"#,
    )
    .expect("parse a");
    let b: SchemaSpec = serde_json::from_str(
        r#"{"tables":[{"columns":[{"primaryKey":true,"nullable":false,"type":"text","name":"id"}],
            "tenantScoped":true,"name":"t"}],"namespace":"acme_app"}"#,
    )
    .expect("parse b");
    assert_eq!(
        hash_of(&a, &[]),
        hash_of(&b, &[]),
        "JSON field order must not affect the hash"
    );

    let c: SchemaSpec = serde_json::from_str(
        r#"{"namespace":"acme_app","tables":[{"name":"t","tenantScoped":true,
            "columns":[{"name":"id","type":"uuid","nullable":false,"primaryKey":true}]}]}"#,
    )
    .expect("parse c");
    assert_ne!(
        hash_of(&a, &[]),
        hash_of(&c, &[]),
        "a semantic change (column type) must change the hash"
    );
}

#[test]
fn hash_detects_live_schema_drift() {
    // The D2 drift guard: the same spec re-planned against a drifted live
    // schema must produce a different hash, or apply's recompute-and-compare
    // can never refuse. Here the drift is the table appearing (created out of
    // band) between plan time (empty namespace) and apply time.
    let s = spec("acme_app", vec![tenant_table("watch")]);
    let fresh = hash_of(&s, &[]);
    let drifted_live = [live_table(
        "acme_app",
        "watch",
        &[
            ("id", "text", false),
            ("payload", "jsonb", false),
            ("tenant_id", "text", false),
        ],
        true,
    )];
    assert_ne!(
        fresh,
        hash_of(&s, &drifted_live),
        "live-schema drift must change the recomputed hash"
    );
}

#[test]
fn hash_treats_column_and_table_order_as_semantic() {
    // Column order IS the CREATE TABLE column order, and table order is the
    // execution order — both must be part of the hash, unlike JSON field
    // order which must not be.
    let two_cols = |first: &str, second: &str| SchemaSpec {
        namespace: Namespace("acme_app".into()),
        tables: vec![TableSpec {
            name: "t".into(),
            comment: None,
            tenant_scoped: true,
            acknowledge_unscoped: false,
            columns: vec![
                col(first, ColumnType::Text, true, false, None),
                col(second, ColumnType::Text, true, false, None),
            ],
            indexes: vec![],
            api_exposed: true,
        }],
    };
    assert_ne!(
        hash_of(&two_cols("a", "b"), &[]),
        hash_of(&two_cols("b", "a"), &[]),
        "column order is semantic and must change the hash"
    );

    let two_tables = |first: &str, second: &str| SchemaSpec {
        namespace: Namespace("acme_app".into()),
        tables: vec![tenant_table(first), tenant_table(second)],
    };
    assert_ne!(
        hash_of(&two_tables("t1", "t2"), &[]),
        hash_of(&two_tables("t2", "t1"), &[]),
        "table order is semantic and must change the hash"
    );
}

#[test]
fn injection_corpus_fails_before_any_generation() {
    let cases: Vec<SchemaSpec> = vec![
        // "; DROP TABLE" in a table name
        spec(
            "acme_app",
            vec![tenant_table("watch\"; DROP TABLE users; --")],
        ),
        // quoted identifier
        spec("acme_app", vec![tenant_table("\"watch\"")]),
        // -- comment terminator in an index name
        {
            let mut t = tenant_table("watch");
            t.indexes.push(IndexSpec {
                name: "idx--evil".into(),
                columns: vec!["id".into()],
                unique: false,
            });
            spec("acme_app", vec![t])
        },
        // nested $$ in an index column
        {
            let mut t = tenant_table("watch");
            t.indexes.push(IndexSpec {
                name: "idx_ok".into(),
                columns: vec!["$$body$$".into()],
                unique: false,
            });
            spec("acme_app", vec![t])
        },
        // unicode homoglyph (non-ASCII) column
        {
            let mut t = tenant_table("watch");
            t.columns
                .push(col("pаyload", ColumnType::Text, true, false, None)); // Cyrillic а
            spec("acme_app", vec![t])
        },
        // reserved namespace
        spec("flint_meta", vec![tenant_table("watch")]),
        // hostile default expression
        {
            let mut t = tenant_table("watch");
            t.columns.push(col(
                "d",
                ColumnType::Text,
                true,
                false,
                Some("''; DROP TABLE x; --'"),
            ));
            spec("acme_app", vec![t])
        },
    ];
    for (i, s) in cases.iter().enumerate() {
        let err = generate(s, &[]).expect_err(&format!("corpus case {i} must be rejected"));
        assert!(
            matches!(err, PlanError::Spec(_)),
            "case {i} rejected at validation, got {err:?}"
        );
    }
}

#[test]
fn type_drift_on_existing_column_is_refused_not_nooped() {
    // Live `payload` is text; the spec says jsonb. Reporting "satisfied"
    // would be a false noop — the generator must refuse toward migrations.
    let live = [live_table(
        "acme_app",
        "watch",
        &[
            ("id", "text", false),
            ("payload", "text", false),
            ("tenant_id", "text", false),
        ],
        true,
    )];
    let err = generate(&spec("acme_app", vec![tenant_table("watch")]), &live)
        .expect_err("type drift must refuse");
    assert!(matches!(
        err,
        PlanError::ColumnDrift { ref column, .. } if column == "payload"
    ));
}

#[test]
fn nullability_drift_is_refused_both_directions() {
    let live = [live_table(
        "acme_app",
        "watch",
        &[
            ("id", "text", true),
            ("payload", "jsonb", false),
            ("tenant_id", "text", false),
        ],
        true,
    )];
    // Spec id is NOT NULL; live id is nullable.
    let err = generate(&spec("acme_app", vec![tenant_table("watch")]), &live)
        .expect_err("nullability drift must refuse");
    assert!(matches!(
        err,
        PlanError::ColumnDrift { ref column, .. } if column == "id"
    ));
}

#[test]
fn live_canonical_type_spellings_still_satisfy_the_spec() {
    // format_type renders `timestamp with time zone`; that must not read as
    // drift against a `timestamptz` spec column.
    let mut t = tenant_table("watch");
    t.columns
        .push(col("filed_at", ColumnType::Timestamptz, true, false, None));
    let live = [live_table(
        "acme_app",
        "watch",
        &[
            ("id", "text", false),
            ("payload", "jsonb", false),
            ("filed_at", "timestamp with time zone", true),
            ("tenant_id", "text", false),
        ],
        true,
    )];
    let plan = generate(&spec("acme_app", vec![t]), &live).expect("canonical spelling matches");
    assert!(
        plan.noop,
        "canonical type spellings must not produce drift:\n{}",
        plan.ddl
    );
}

#[test]
fn caller_index_may_not_shadow_the_generated_tenant_index() {
    let mut t = tenant_table("watch");
    t.indexes.push(IndexSpec {
        name: "watch_tenant_idx".into(),
        columns: vec!["id".into()],
        unique: false,
    });
    let err = generate(&spec("acme_app", vec![t]), &[]).expect_err("reserved index name");
    assert!(matches!(
        err,
        PlanError::Spec(SpecError::ReservedIndexName(ref n)) if n == "watch_tenant_idx"
    ));
}

#[test]
fn reserved_namespace_error_names_the_namespace() {
    let err = generate(&spec("pg_catalog", vec![tenant_table("t")]), &[]).expect_err("reserved");
    assert!(matches!(
        err,
        PlanError::Spec(SpecError::ReservedNamespace(ref ns)) if ns == "pg_catalog"
    ));
}
