//! Generated `Host` trait bindings for `flint:host`'s governed capability
//! interfaces (db, llm, kv, identity, secrets).
//!
//! See `wit/flint/host/world.wit`'s `host-bindings` world — a host-only
//! aggregation world kept separate from `edge-function` so this codegen
//! doesn't also need to resolve `wasi:http` (already generated by
//! `wasmtime-wasi-http` and reused via `ProxyPre` elsewhere in this crate).
#![allow(clippy::all, clippy::pedantic)] // generated code, not hand-written

wasmtime::component::bindgen!({
    path: "../../wit/flint/host",
    world: "host-bindings",
    imports: {
        "flint:host/db": async,
        "flint:host/llm": async,
        "flint:host/secrets": async,
        // kv and identity are plain in-memory / RlsContext reads — no host
        // I/O, so they stay on the default (synchronous) codegen path.
    },
    with: {
        "flint:host/secrets.secret": crate::secrets::SecretHandle,
    },
});
