//! Plain (non-GraphQL) route handlers: health, OpenAPI/MCP tool docs, vector RPC.
//!
//! Relocated from `main.rs` (p16 file-size split) — behavior unchanged.

use axum::{
    extract::State,
    http::{HeaderMap, StatusCode},
    response::{IntoResponse, Json},
};
use serde_json::json;

use fdb_auth::rls_from_bearer;
use fdb_domain::VectorRpcRequest;

use crate::graphql::extract_bearer;
use crate::GatewayState;

#[tracing::instrument(skip(state), fields(service = "flint-quarry"))]
pub(crate) async fn healthz(State(state): State<GatewayState>) -> Json<serde_json::Value> {
    let compiled = state.state_manager.current();
    Json(json!({
        "status": "ok",
        "service": "flint-quarry",
        "schema_version": compiled.version,
    }))
}

/// GET /openapi.json — serve the compiled OpenAPI 3.1.0 document.
///
/// No authentication required — OpenAPI docs are public, same pattern as
/// Supabase's `/rest/v1/` OpenAPI endpoint. The document is pre-compiled by
/// `OpenApiCompiler::compile()` during `StateManager::do_compile()` and hot-swapped
/// on DDL changes. Callers always receive the schema consistent with the live
/// database state at the time of the request.
#[tracing::instrument(skip(state))]
pub(crate) async fn openapi_handler(State(state): State<GatewayState>) -> Json<serde_json::Value> {
    let compiled = state.state_manager.current();
    Json(compiled.openapi_doc.clone())
}

/// GET /mcp/v1/tools — serve compiled MCP tool definitions from `DatabaseModel`.
///
/// Returns the MCP `tools/list` result generated by `McpCompiler`. Hot-swapped
/// on DDL changes. Protected by JWT auth via `require_rls`.
pub(crate) async fn mcp_tools_handler(
    State(state): State<GatewayState>,
) -> Json<serde_json::Value> {
    let compiled = state.state_manager.current();
    Json(compiled.mcp_tools_doc.clone())
}

/// POST /rpc/vector — vector similarity search via pgvector `<=>` operator.
///
/// Accepts a `VectorRpcRequest` body, executes under the full 6-GUC RLS context,
/// and returns a JSON array of rows ordered by ascending cosine distance.
pub(crate) async fn rpc_vector_handler(
    State(state): State<GatewayState>,
    headers: HeaderMap,
    Json(body): Json<VectorRpcRequest>,
) -> impl IntoResponse {
    let Some(bearer) = extract_bearer(&headers) else {
        return (
            StatusCode::UNAUTHORIZED,
            Json(json!({"error": "missing Authorization header"})),
        )
            .into_response();
    };
    let rls = match rls_from_bearer(&bearer).await {
        Ok(ctx) => ctx,
        Err(e) => {
            tracing::warn!(error = %e, "bearer verification failed for /rpc/vector");
            return (
                StatusCode::UNAUTHORIZED,
                Json(json!({"error": "invalid or expired token"})),
            )
                .into_response();
        }
    };
    match state.vector_rpc.execute_similarity(&body, &rls).await {
        Ok(rows) => Json(rows).into_response(),
        Err(fdb_ports::BackendError::Query(msg)) => {
            (StatusCode::BAD_REQUEST, Json(json!({"error": msg}))).into_response()
        }
        Err(e) => {
            tracing::error!(error = %e, "vector similarity error");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({"error": "internal server error"})),
            )
                .into_response()
        }
    }
}
